version: '3.7'
volumes:
    logs:
        driver: local
    mariadb-data:
services:
  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
  slim:
      build: ./docker/slim
      working_dir: /var/www
      tty: true
      command: php -S 0.0.0.0:8080 -t public
      environment:
        docker: "true"
      ports:
        - "8080:8080"
      volumes:
        - .:/var/www
        - logs:/var/www/logs
  composer:
      image: composer:1.9.3
      environment:
        - COMPOSER_CACHE_DIR=/app/.cache/composer
      volumes:
        - .:/app
      restart: never
    # NEW IN THIS SECTION!!!
